### PR TITLE
fix: update patches to latest from emacs-plus

### LINKED ISSUE #7: Patches no longer apply successfully with latest upstream commits
The macOS-specific patches no longer apply cleanly on recent Emacs upstream commits, causing builds to fail.

Originally noted in https://github.com/cmacrae/emacs/pull/6#issuecomment-1002633614.

We may be able to reference @d12frosted's latest patch updates in `emacs-plus`. The v29 patches are symlinked to the patches in the v28 directory:

- https://github.com/d12frosted/homebrew-emacs-plus/blob/aaf5811a00bf2a826fbe8d91a24f9e5029af1e97/patches/emacs-28/no-titlebar.patch
- https://github.com/d12frosted/homebrew-emacs-plus/blob/aaf5811a00bf2a826fbe8d91a24f9e5029af1e97/patches/emacs-28/system-appearance.patch

Also see https://github.com/sagittaros/emacs-osx/issues/5 – looks like they're running into a similar or identical issue with patches.

Here's the relevant section from the latest workflow run:

https://github.com/cmacrae/emacs/runs/4725513857?check_suite_focus=true

```
emacs> unpacking sources
emacs> unpacking source archive /nix/store/7jnpakz058kq0dwi0wllxxlif5py1hsc-source
emacs> source root is source
emacs> patching sources
emacs> applying patch /nix/store/j9fa4phwrah4rwg3va7whlxljf8qbxba-fix-window-role.patch
emacs> patching file src/nsterm.m
emacs> Hunk #1 succeeded at 8634 (offset -244 lines).
emacs> applying patch /nix/store/nlgq5vra3c0r1snj0wbmd49r78pagi5j-no-titlebar.patch
emacs> patching file src/nsterm.m
emacs> Hunk #1 FAILED at 433.
emacs> Hunk #2 succeeded at 8353 (offset 48 lines).
emacs> 1 out of 2 hunks FAILED -- saving rejects to file src/nsterm.m.rej
error: builder for '/nix/store/880sh2mrn0gsdwx1kmbq54d3iddcf39n-emacs-29.0.50.drv' failed with exit code 1;
       last 10 log lines:
       > source root is source
       > patching sources
       > applying patch /nix/store/j9fa4phwrah4rwg3va7whlxljf8qbxba-fix-window-role.patch
       > patching file src/nsterm.m
       > Hunk #1 succeeded at 8634 (offset -244 lines).
       > applying patch /nix/store/nlgq5vra3c0r1snj0wbmd49r78pagi5j-no-titlebar.patch
       > patching file src/nsterm.m
       > Hunk #1 FAILED at 433.
       > Hunk #2 succeeded at 8353 (offset 48 lines).
       > 1 out of 2 hunks FAILED -- saving rejects to file src/nsterm.m.rej
       For full logs, run 'nix log /nix/store/880sh2mrn0gsdwx1kmbq54d3iddcf39n-emacs-29.0.50.drv'.
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by montchr**
Fixes #7 

- Updates the `fix-window-role` patch to the latest available version in emacs-plus
- Removes the `no-titlebar` patch entirely, adding a section to the README explaining that the patch can be replaced with Elisp.

### CODE REVIEW

**Comment by montchr** [comment]
Ha, too late – these are broken too!

https://github.com/d12frosted/homebrew-emacs-plus/issues/433

**Comment by montchr** [comment]
Looks like the build might be running successfully after removing the `no-titlebar` patch. As it turns out, the patch might not be necessary considering the following elisp snippet appears to have the desired effect:

```emacs-lisp
(add-to-list 'default-frame-alist '(undecorated . t))
```

**Comment by montchr** [comment]
_several hours later…_

Looks like Emacs built successfully, but the workflow run failed because my fork is not authorized to push to this repo's binary cache:

```
cachix: FailureResponse (Request {requestPath = (BaseUrl {baseUrlScheme = Https, baseUrlHost = "cachix.org", baseUrlPort = 443, baseUrlPath = ""},"/api/v1/cache/emacs/8lgdnr9ybv7kpnw2qysbifzwc2ljs15p.narinfo"), requestQueryString = fromList [], requestBody = Just ((),application/json;charset=utf-8), requestAccept = fromList [], requestHeaders = fromList [("Authorization","<REDACTED>")]), requestHttpVersion = HTTP/1.1, requestMethod = "POST"} (Response {responseStatusCode = Status {statusCode = 401, statusMessage = "Unauthorized"}, responseHeaders = fromList [("Date","Wed, 02 Feb 2022 07:09:00 GMT"),("Transfer-Encoding","chunked"),("Connection","keep-alive"),("Cache-Control","no-cache"),("CF-Cache-Status","DYNAMIC"),("Expect-CT","max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""),("Report-To","{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=k%2FtAfYda1BlvZMxxzTMqr5WWMZ%2FWybXHDWnpjFAkYWbktcbKf5EoVRUamLDmE6r0zhe5gn%2B6HtHu48g7Tj7qYel5W%2F33sgnGKqRnNRSPa9WDHTwcmg%2FYTDowzek%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}"),("NEL","{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}"),("Server","cloudflare"),("CF-RAY","6d71976bfc1681c4-IAD")], responseHttpVersion = HTTP/1.1, responseBody = "Binary cache emacs doesn't exist or you're not authorized to access. Please check the name for typos and/or provide an auth token. Contact support on cachix.org if you're stuck!"})
```

**Comment by montchr** [comment]
@cmacrae Ready for review when you have some time. And I'm not sure what is the best way to fix the Cachix push, but I think that'd resolve itself once merged.

What do you think about the approach of removing the `no-titlebar` patch? From the update I made to the README:

> The `no-titlebar` frame patch has been removed, as it can be implemented with
pure Emacs Lisp by putting the following early on during initialization (e.g. in
`early-init.el`):
>
> ```emacs-lisp
> (add-to-list 'default-frame-alist '(undecorated . t))
> ```
>
> See https://github.com/d12frosted/homebrew-emacs-plus/issues/433#issuecomment-1025547880 for further background.

I've tested this approach locally and it works well! Here's a demo of its behavior with yabai v4 with only the single `fix-window-role` patch applied in addition to the snippet above:

CleanShot 2022-02-02 at 09 19 01

**Comment by cmacrae** [comment]
Ah! My sincere apologies @montchr - I've been on a bit of a hiatus and hadn't seen this.
Thank you for your contributions :) I'll have a look over them shortly

**Comment by cmacrae** [comment]
Passed on `master`. Thanks so much @montchr 🙌 It's nice to get rid of the no-titlebars patch

**Pull request merged**
